module.exports = {
  shipments: [
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T11:41:19+03:00',
      deducted: 'N',
      deliveryId: '41',
      deliveryName: 'СДЭК (Доставка курьером)',
      id: '3071',
      orderId: '1535',
      statusId: 'DN',
      trackingNumber: 'CDEK 1217151896',
      items: [
        {
          detailPageUrl:
            '/krasiteli/lyuminestsentnye-krasiteli/goluboy-fotolyuminestsentnyy-pigment-lumy-20g-/',
          id: '15420',
          measureName: 'шт',
          name: 'Голубой фотолюминесцентный пигмент Lumy+ (20г)',
          orderId: '1535',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/lyuminestsentnye-krasiteli/zelenyy-fotolyuminestsentnyy-pigment-lumy-20g/',
          id: '15421',
          measureName: 'шт',
          name: 'Зеленый фотолюминесцентный пигмент Lumy+ (20г)',
          orderId: '1535',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/epoksidnaya-smola/smola-dlya-zalivki/smola-dlya-stoleshnits/epoxymax-dekor-1-35kg04022388/',
          id: '15429',
          measureName: 'шт',
          name: 'Прозрачная эпоксидная смола EpoximaxX DECOR 1,35 кг',
          orderId: '1535',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-04T17:38:48+03:00',
      deducted: 'N',
      deliveryId: '42',
      deliveryName: 'СДЭК (Самовывоз)',
      id: '3073',
      orderId: '1536',
      statusId: 'DN',
      trackingNumber: 'CDEK 1216963160',
      items: [
        {
          detailPageUrl:
            '/epoksidnaya-smola/smola-dlya-khudozhestvennykh-rabot/smola-dlya-risovaniya/nabor-dlya-risovaniya-s-prozrachnoy-epoksidnoy-smoloy-mixart-resin-box-standart/',
          id: '15417',
          measureName: 'шт',
          name:
            'Набор STANDART для рисования. C прозрачной эпоксидной смолой MixArt Resin BOX',
          orderId: '1536',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/glittery/metallizirovannye-pigmenty/glitter-iskristoe-zoloto-5-ml/',
          id: '15422',
          measureName: 'шт',
          name: 'Глиттер искристое золото, 5 мл',
          orderId: '1536',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/prozrachnye-krasiteli/krasitel-epoximaxx-colour-15-g-siniy/',
          id: '15423',
          measureName: 'шт',
          name: 'Краситель EpoximaxX Colour! 15 г синий',
          orderId: '1536',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/prozrachnye-krasiteli/krasitel-epoximaxx-colour-15-g-chyernyy/',
          id: '15424',
          measureName: 'шт',
          name: 'Краситель EpoximaxX Colour! 15 г чёрный',
          orderId: '1536',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/prozrachnye-krasiteli/krasitel-epoximaxx-colour-15-g-morskaya-volna/',
          id: '15425',
          measureName: 'шт',
          name: 'Краситель EpoximaxX Colour! 15 г морская волна',
          orderId: '1536',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/fluorestsentnye-krasiteli/krasitel-epoximaxx-colour-15-g-fluo-zelenyy/',
          id: '15426',
          measureName: 'шт',
          name: 'Краситель EpoximaxX Colour! 15 г флуо. зеленый',
          orderId: '1536',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/neprozrachnye-matovye-krasiteli/krasitel-epoximaxx-colour-15-g-belyy/',
          id: '15427',
          measureName: 'шт',
          name: 'Краситель EpoximaxX Colour! 15 г белый',
          orderId: '1536',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/lyuminestsentnye-krasiteli/goluboy-fotolyuminestsentnyy-pigment-lumy-20g-/',
          id: '15428',
          measureName: 'шт',
          name: 'Голубой фотолюминесцентный пигмент Lumy+ (20г)',
          orderId: '1536',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/perlamutrovye-krasiteli/krasitel_tsvet_chernyy_zhemchug_15_g/',
          id: '15431',
          measureName: 'шт',
          name: 'Краситель цвет - черный жемчуг (15 г)',
          orderId: '1536',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/perlamutrovye-krasiteli/krasitel-tsvet-tiffani-15-g/',
          id: '15432',
          measureName: 'шт',
          name: 'Краситель цвет - тиффани (15 г)',
          orderId: '1536',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/prozrachnye-krasiteli/krasitel-epoximaxx-colour-15-g-krasnyy/',
          id: '15433',
          measureName: 'шт',
          name: 'Краситель EpoximaxX Colour! 15 г красный',
          orderId: '1536',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/lyuminestsentnye-krasiteli/zelenyy-fotolyuminestsentnyy-pigment-lumy-20g/',
          id: '15434',
          measureName: 'шт',
          name: 'Зеленый фотолюминесцентный пигмент Lumy+ (20г)',
          orderId: '1536',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-04T18:19:11+03:00',
      deducted: 'N',
      deliveryId: '41',
      deliveryName: 'СДЭК (Доставка курьером)',
      id: '3079',
      orderId: '1539',
      statusId: 'DN',
      trackingNumber: 'CDEK 1216971118',
      items: [
        {
          detailPageUrl:
            '/epoksidnaya-smola/smola-dlya-dekora-i-tvorchestva/yuvelirnaya-smola/komplekt-epoxy-crystal-plus-580gr2801/',
          id: '14346',
          measureName: 'шт',
          name:
            'Ювелирная прозрачная эпоксидная смола Epoximaxx Epoxy Crystal PLUS, 580 г',
          orderId: '1539',
          quantity: '1.0000',
        },
        {
          detailPageUrl: '/silikonovye-moldy/mold-dlya-ukrasheniy-2-elochki/',
          id: '14347',
          measureName: 'шт',
          name: 'Молд для украшений "2 елочки"',
          orderId: '1539',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/silikonovye-moldy/mold-dlya-ukrasheniy-2-treugolnika/',
          id: '14348',
          measureName: 'шт',
          name: 'Молд для украшений "2 треугольника"',
          orderId: '1539',
          quantity: '1.0000',
        },
        {
          detailPageUrl: '/silikonovye-moldy/dom-s-santoy-14-sm/',
          id: '15452',
          measureName: 'шт',
          name: 'Силиконовый молд Дом с Сантой 14 см',
          orderId: '1539',
          quantity: '1.0000',
        },
        {
          detailPageUrl: '/silikonovye-moldy/mold-dlya-ukrasheniy-zvyezdy/',
          id: '15453',
          measureName: 'шт',
          name: 'Молд для украшений "Звёзды"',
          orderId: '1539',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T12:49:48+03:00',
      deducted: 'N',
      deliveryId: '42',
      deliveryName: 'СДЭК (Самовывоз)',
      id: '3091',
      orderId: '1545',
      statusId: 'DN',
      trackingNumber: 'CDEK 1217162060',
      items: [
        {
          detailPageUrl:
            '/krasiteli/lyuminestsentnye-krasiteli/zelenyy-fotolyuminestsentnyy-pigment-lumy-20g/',
          id: '15518',
          measureName: 'шт',
          name: 'Зеленый фотолюминесцентный пигмент Lumy+ (20г)',
          orderId: '1545',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/lyuminestsentnye-krasiteli/oranzhevyy-fotolyuminestsentnyy-pigment-lumy-20g/',
          id: '15519',
          measureName: 'шт',
          name: 'Оранж. фотолюминесцентный пигмент Lumy+ (20г)',
          orderId: '1545',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/lyuminestsentnye-krasiteli/krasnyy-fotolyuminestsentnyy-pigment-lumy-20g/',
          id: '15520',
          measureName: 'шт',
          name: 'Красный фотолюминесцентный пигмент Lumy+ (20г)',
          orderId: '1545',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/lyuminestsentnye-krasiteli/goluboy-fotolyuminestsentnyy-pigment-lumy-20g-/',
          id: '15521',
          measureName: 'шт',
          name: 'Голубой фотолюминесцентный пигмент Lumy+ (20г)',
          orderId: '1545',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/furnitura/nabor-blestok-i-dekorativnykh-napolniteley/',
          id: '15522',
          measureName: 'шт',
          name: 'Набор блесток и декоративных наполнителей. 48 шт',
          orderId: '1545',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T13:25:52+03:00',
      deducted: 'N',
      deliveryId: '47',
      deliveryName: 'Самовывоз со склада-магазина',
      id: '3097',
      orderId: '1548',
      statusId: 'DN',
      trackingNumber: 'SAV 8121548 ',
      items: [
        {
          detailPageUrl:
            '/artbordy-i-planshety/artbord-doska-dlya-syerfa-13kh55-sm/',
          id: '15360',
          measureName: 'шт',
          name: 'Артборд доска для сёрфа, 13х55 см',
          orderId: '1548',
          quantity: '1.0000',
        },
        {
          detailPageUrl: '/artbordy-i-planshety/5-artbordov-kruglye-30kh30-sm/',
          id: '15549',
          measureName: 'шт',
          name: '5 артбордов, круглые 30х30 см',
          orderId: '1548',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T13:30:44+03:00',
      deducted: 'N',
      deliveryId: '42',
      deliveryName: 'СДЭК (Самовывоз)',
      id: '3099',
      orderId: '1549',
      statusId: 'DN',
      trackingNumber: 'CDEK 1217167729',
      items: [
        {
          detailPageUrl:
            '/epoksidnaya-smola/smola-dlya-khudozhestvennykh-rabot/smola-dlya-risovaniya/nabor-dlya-risovaniya-mixart-mini-box-morskoy-bereg/',
          id: '3654',
          measureName: 'шт',
          name: 'Мини набор для рисования смолой МОРСКОЙ БЕРЕГ',
          orderId: '1549',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T13:32:06+03:00',
      deducted: 'N',
      deliveryId: '47',
      deliveryName: 'Самовывоз со склада-магазина',
      id: '3101',
      orderId: '1550',
      statusId: 'DN',
      trackingNumber: 'SAV 8121550 ',
      items: [
        {
          detailPageUrl:
            '/epoksidnaya-smola/smola-dlya-khudozhestvennykh-rabot/smola-dlya-risovaniya/nabor-dlya-risovaniya-mixart-resin-box/',
          id: '15555',
          measureName: 'шт',
          name:
            'Premium набор для рисования MixArt Resin BOX. C прозрачной эпоксидной смолой.',
          orderId: '1550',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T13:39:11+03:00',
      deducted: 'N',
      deliveryId: '47',
      deliveryName: 'Самовывоз со склада-магазина',
      id: '3109',
      orderId: '1554',
      statusId: 'DN',
      trackingNumber: 'SAV 8121554 ',
      items: [
        {
          detailPageUrl:
            '/instrument-i-sredstva-zashchity/razdelitelnaya-smazka-vs-m/',
          id: '15712',
          measureName: 'шт',
          name: '﻿Разделительная смазка Вс-М(180 г)',
          orderId: '1554',
          quantity: '10.0000',
        },
        {
          detailPageUrl: '/instrument-i-sredstva-zashchity/ease-release-200/',
          id: '15713',
          measureName: 'шт',
          name: 'Разделительный состав. Ease Release 200 (341 г)',
          orderId: '1554',
          quantity: '5.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T13:47:15+03:00',
      deducted: 'N',
      deliveryId: '53',
      deliveryName: 'Курьером в день заказа',
      id: '3113',
      orderId: '1556',
      statusId: 'DN',
      trackingNumber: '',
      items: [
        {
          detailPageUrl:
            '/epoksidnaya-smola/smola-dlya-khudozhestvennykh-rabot/smola-dlya-risovaniya/prozrachnaya-epoksidnaya-smola-dlya-risovaniya-mixart-resin-4-5-kg/',
          id: '15751',
          measureName: 'шт',
          name:
            'Прозрачная эпоксидная смола для рисования MixArt Resin. 4,5 кг.',
          orderId: '1556',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/glittery/metallizirovannye-pigmenty/glitter-siniy-okean-5-ml/',
          id: '15752',
          measureName: 'шт',
          name: 'Глиттер синий океан, 5 мл',
          orderId: '1556',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/prozrachnye-krasiteli/krasitel-epoximaxx-colour-15-g-morskaya-volna/',
          id: '15753',
          measureName: 'шт',
          name: 'Краситель EpoximaxX Colour! 15 г морская волна',
          orderId: '1556',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/perlamutrovye-krasiteli/krasitel_tsvet_zheltyy_spelyy_limon_15_g/',
          id: '15755',
          measureName: 'шт',
          name: 'Краситель цвет - желтый спелый лимон (15 г)',
          orderId: '1556',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/perlamutrovye-krasiteli/krasitel_tsvet_chernyy_zhemchug_15_g/',
          id: '15757',
          measureName: 'шт',
          name: 'Краситель цвет - черный жемчуг (15 г)',
          orderId: '1556',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/perlamutrovye-krasiteli/krasitel_tsvet_iskristyy_mertsayushchiy_belyy_15_g/',
          id: '15758',
          measureName: 'шт',
          name: 'Краситель цвет - серебристый белый жемчуг (15 г)',
          orderId: '1556',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/instrument-i-sredstva-zashchity/silikonovye-palochki-dlya-smeshivaniya-nabor-iz-2-sht/',
          id: '15763',
          measureName: 'шт',
          name: 'Силиконовые палочки для работы 2 шт 12 см',
          orderId: '1556',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T14:40:45+03:00',
      deducted: 'N',
      deliveryId: '49',
      deliveryName: 'Главпункт (Пункты выдачи)',
      id: '3115',
      orderId: '1557',
      statusId: 'DN',
      trackingNumber: '',
      items: [
        {
          detailPageUrl:
            '/silikonovye-moldy/cilikonovye-moldy-oblozhki-bloknota-a5-6-7-3-sht/',
          id: '15762',
          measureName: 'шт',
          name: 'Cиликоновые молды "Обложки блокнота A5/6/7" 3 шт',
          orderId: '1557',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T14:37:18+03:00',
      deducted: 'N',
      deliveryId: '49',
      deliveryName: 'Главпункт (Пункты выдачи)',
      id: '3117',
      orderId: '1558',
      statusId: 'DN',
      trackingNumber: '',
      items: [
        {
          detailPageUrl:
            '/formovochni-silikon/silikon-na-osnove-olova/silikon-mastermold-s30-1-kg/',
          id: '15769',
          measureName: 'шт',
          name: 'Силикон MasterMold S30 (1,05 кг)',
          orderId: '1558',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T14:30:12+03:00',
      deducted: 'N',
      deliveryId: '42',
      deliveryName: 'СДЭК (Самовывоз)',
      id: '3119',
      orderId: '1559',
      statusId: 'DN',
      trackingNumber: 'CDEK 1217176178',
      items: [
        {
          detailPageUrl:
            '/silikonovye-moldy/cilikonovye-moldy-oblozhki-bloknota-a5-6-7-3-sht/',
          id: '15770',
          measureName: 'шт',
          name: 'Cиликоновые молды "Обложки блокнота A5/6/7" 3 шт',
          orderId: '1559',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/epoksidnaya-smola/prozrachnaya-smola-epoximaxx-epoxy-crystal-plus-695-g-premium-nabor/',
          id: '15772',
          measureName: 'шт',
          name:
            'Прозрачная смола Epoximaxx Epoxy Crystal PLUS, 695 г (Premium набор)',
          orderId: '1559',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/alkogolnye-chernila/alkogolnye-chernila-white-ink-20-ml/',
          id: '15773',
          measureName: 'шт',
          name: 'Алкогольные чернила "White ink" 20 мл',
          orderId: '1559',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/furnitura/nabor-blestok-i-dekorativnykh-napolniteley/',
          id: '15775',
          measureName: 'шт',
          name: 'Набор блесток и декоративных наполнителей. 48 шт',
          orderId: '1559',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T14:21:04+03:00',
      deducted: 'N',
      deliveryId: '47',
      deliveryName: 'Самовывоз со склада-магазина',
      id: '3123',
      orderId: '1561',
      statusId: 'DN',
      trackingNumber: '',
      items: [
        {
          detailPageUrl: '/silikonovye-moldy/mold-dlya-ukrasheniy-lampochka/',
          id: '15779',
          measureName: 'шт',
          name: 'Молд для украшений "Лампочка"',
          orderId: '1561',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T15:11:58+03:00',
      deducted: 'N',
      deliveryId: '42',
      deliveryName: 'СДЭК (Самовывоз)',
      id: '3133',
      orderId: '1566',
      statusId: 'DN',
      trackingNumber: 'CDEK 1217181834',
      items: [
        {
          detailPageUrl:
            '/epoksidnaya-smola/nabor-novichka-premium-s-epoxy-crystal-plus-115-g/',
          id: '15862',
          measureName: 'шт',
          name: 'Набор новичка PREMIUM с Epoxy Crystal PLUS, 115 г',
          orderId: '1566',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T15:12:57+03:00',
      deducted: 'N',
      deliveryId: '42',
      deliveryName: 'СДЭК (Самовывоз)',
      id: '3139',
      orderId: '1569',
      statusId: 'DN',
      trackingNumber: 'CDEK 1217181960',
      items: [
        {
          detailPageUrl:
            '/epoksidnaya-smola/smola-dlya-zalivki/smola-dlya-stoleshnits/epoxymax-dekor-4kg1102/',
          id: '15806',
          measureName: 'шт',
          name: 'Прозрачная эпоксидная смола EpoximaxX DECOR, 4 кг',
          orderId: '1569',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/lyuminestsentnye-krasiteli/zelenyy-fotolyuminestsentnyy-pigment-lumy-20g/',
          id: '15808',
          measureName: 'шт',
          name: 'Зеленый фотолюминесцентный пигмент Lumy+ (20г)',
          orderId: '1569',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/lyuminestsentnye-krasiteli/goluboy-fotolyuminestsentnyy-pigment-lumy-20g-/',
          id: '15809',
          measureName: 'шт',
          name: 'Голубой фотолюминесцентный пигмент Lumy+ (20г)',
          orderId: '1569',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/lyuminestsentnye-krasiteli/krasnyy-fotolyuminestsentnyy-pigment-lumy-20g/',
          id: '15810',
          measureName: 'шт',
          name: 'Красный фотолюминесцентный пигмент Lumy+ (20г)',
          orderId: '1569',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/prozrachnye-krasiteli/krasitel-epoximaxx-colour-15-g-krasnyy/',
          id: '15868',
          measureName: 'шт',
          name: 'Краситель EpoximaxX Colour! 15 г красный',
          orderId: '1569',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/prozrachnye-krasiteli/krasitel-epoximaxx-colour-15-g-siniy/',
          id: '15875',
          measureName: 'шт',
          name: 'Краситель EpoximaxX Colour! 15 г синий',
          orderId: '1569',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/prozrachnye-krasiteli/krasitel-epoximaxx-colour-15-g-zelenyy/',
          id: '15876',
          measureName: 'шт',
          name: 'Краситель EpoximaxX Colour! 15 г зеленый',
          orderId: '1569',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T15:14:17+03:00',
      deducted: 'N',
      deliveryId: '42',
      deliveryName: 'СДЭК (Самовывоз)',
      id: '3141',
      orderId: '1570',
      statusId: 'DN',
      trackingNumber: 'CDEK 1217182109',
      items: [
        {
          detailPageUrl:
            '/krasiteli/prozrachnye-krasiteli/nabor-pigmentov-epoximaxx-colour-morskoy-10-sht/',
          id: '15727',
          measureName: 'шт',
          name: 'Набор пигментов EpoximaxX Colour! Морской 10 шт',
          orderId: '1570',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/pastelnye-krasiteli/krasitel-epoximaxx-colour-15-g-pastelnyy-zelenyy/',
          id: '15728',
          measureName: 'шт',
          name: 'Краситель EpoximaxX Colour! 15 г пастельный зеленый',
          orderId: '1570',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/alkogolnye-chernila/alkogolnye-chernila-midhight-ink-20-ml/',
          id: '15733',
          measureName: 'шт',
          name: 'Алкогольные чернила "Midnight Ink" 20 мл',
          orderId: '1570',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/fluorestsentnye-krasiteli/krasitel-epoximaxx-colour-15-g-fluo-zheltyy/',
          id: '15734',
          measureName: 'шт',
          name: 'Краситель EpoximaxX Colour! 15 г флуо. желтый',
          orderId: '1570',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/perlamutrovye-krasiteli/krasitel-tsvet-tiffani-15-g/',
          id: '15737',
          measureName: 'шт',
          name: 'Краситель цвет - тиффани (15 г)',
          orderId: '1570',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T16:39:52+03:00',
      deducted: 'N',
      deliveryId: '41',
      deliveryName: 'СДЭК (Доставка курьером)',
      id: '3151',
      orderId: '1575',
      statusId: 'DN',
      trackingNumber: 'CDEK 1217194858',
      items: [
        {
          detailPageUrl: '/silikonovye-moldy/silikonovyy-mold-geoda-oblaka/',
          id: '15977',
          measureName: 'шт',
          name: 'Силиконовый молд "Жеоды" 5 в 1 (31*25 см)',
          orderId: '1575',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T15:35:22+03:00',
      deducted: 'N',
      deliveryId: '42',
      deliveryName: 'СДЭК (Самовывоз)',
      id: '3153',
      orderId: '1576',
      statusId: 'DN',
      trackingNumber: 'CDEK 1217185809',
      items: [
        {
          detailPageUrl:
            '/silikonovye-moldy/silikonovye-moldy-koltsa-3-vida-17-mm/',
          id: '15994',
          measureName: 'шт',
          name: 'Силиконовые молды кольца 3 вида 17 мм',
          orderId: '1576',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/silikonovye-moldy/silikonovyy-mold-podstakannik-s-ostrymi-granyami-9-sm/',
          id: '15997',
          measureName: 'шт',
          name: 'Силиконовый молд Подстаканник с острыми гранями 9 см',
          orderId: '1576',
          quantity: '1.0000',
        },
        {
          detailPageUrl: '/sukhotsvety/sun-flower-sukhotsvet-20-30-tsvetkov/',
          id: '16002',
          measureName: 'шт',
          name: 'Sun flower, сухоцвет, 55-60 цветков',
          orderId: '1576',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T15:36:39+03:00',
      deducted: 'N',
      deliveryId: '42',
      deliveryName: 'СДЭК (Самовывоз)',
      id: '3157',
      orderId: '1578',
      statusId: 'DN',
      trackingNumber: 'CDEK 1217185979',
      items: [
        {
          detailPageUrl:
            '/silikonovye-moldy/cilikonovye-moldy-oblozhki-bloknota-a5-6-7-3-sht/',
          id: '16006',
          measureName: 'шт',
          name: 'Cиликоновые молды "Обложки блокнота A5/6/7" 3 шт',
          orderId: '1578',
          quantity: '1.0000',
        },
        {
          detailPageUrl: '/silikonovye-moldy/silikonovyy-mold-piramida-5-5sm/',
          id: '16007',
          measureName: 'шт',
          name: 'Силиконовый молд ПИРАМИДА 5*5см',
          orderId: '1578',
          quantity: '1.0000',
        },
        {
          detailPageUrl: '/artbordy-i-planshety/artbord-edinorog-25kh30-sm/',
          id: '16008',
          measureName: 'шт',
          name: 'Артборд единорог, 25х30 см',
          orderId: '1578',
          quantity: '1.0000',
        },
        {
          detailPageUrl: '/silikonovye-moldy/silikonovyy-mold-ruchka-2/',
          id: '16009',
          measureName: 'шт',
          name: 'Силиконовый молд Ручка №2',
          orderId: '1578',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/silikonovye-moldy/silikonovyy-mold-sfera-sostavnaya-5-sm/',
          id: '16010',
          measureName: 'шт',
          name: 'Силиконовый молд Сфера составная 5 см',
          orderId: '1578',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T15:47:20+03:00',
      deducted: 'N',
      deliveryId: '42',
      deliveryName: 'СДЭК (Самовывоз)',
      id: '3163',
      orderId: '1581',
      statusId: 'DN',
      trackingNumber: 'CDEK 1217187747',
      items: [
        {
          detailPageUrl:
            '/epoksidnaya-smola/smola-dlya-dekora-i-tvorchestva/yuvelirnaya-smola/epoximaxx-yuvelirochka-prozrachnaya-smola-345-g/',
          id: '16035',
          measureName: 'шт',
          name: 'EpoximaxX Ювелирочка, прозрачная смола 345 г',
          orderId: '1581',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/epoksidnaya-smola/smola-dlya-dekora-i-tvorchestva/yuvelirnaya-smola/yuvelirnaya-prozrachnaya-epoksidnaya-smola-epoximaxx-epoxy-crystal-plus-580-g-2-sht-/',
          id: '16036',
          measureName: 'шт',
          name:
            'Ювелирная прозрачная эпоксидная смола Epoximaxx Epoxy Crystal PLUS, 580 г, 2 шт.',
          orderId: '1581',
          quantity: '1.0000',
        },
        {
          detailPageUrl: '/silikonovye-moldy/mold-dlya-ukrasheniy-treugolnik/',
          id: '16037',
          measureName: 'шт',
          name: 'Молд для украшений "Треугольник"',
          orderId: '1581',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/silikonovye-moldy/mold-dlya-ukrasheniy-sergi-s-treugolnikom/',
          id: '16038',
          measureName: 'шт',
          name: 'Молд для украшений "Серьги с треугольником"',
          orderId: '1581',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T16:09:00+03:00',
      deducted: 'N',
      deliveryId: '42',
      deliveryName: 'СДЭК (Самовывоз)',
      id: '3165',
      orderId: '1582',
      statusId: 'DN',
      trackingNumber: 'CDEK 1217187914',
      items: [
        {
          detailPageUrl:
            '/silikonovye-moldy/mold-dlya-ukrasheniy-2-treugolnika/',
          id: '15503',
          measureName: 'шт',
          name: 'Молд для украшений "2 треугольника"',
          orderId: '1582',
          quantity: '1.0000',
        },
        {
          detailPageUrl: '/silikonovye-moldy/mold-dlya-ukrasheniy-treugolnik/',
          id: '15516',
          measureName: 'шт',
          name: 'Молд для украшений "Треугольник"',
          orderId: '1582',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T16:10:25+03:00',
      deducted: 'N',
      deliveryId: '42',
      deliveryName: 'СДЭК (Самовывоз)',
      id: '3167',
      orderId: '1583',
      statusId: 'DN',
      trackingNumber: 'CDEK 1217191014',
      items: [
        {
          detailPageUrl:
            '/epoksidnaya-smola/smola-dlya-khudozhestvennykh-rabot/smola-dlya-risovaniya/prozrachnaya-epoksidnaya-smola-dlya-risovaniya-mixart-resin-1-5-kg/',
          id: '16057',
          measureName: 'шт',
          name:
            'Прозрачная эпоксидная смола для рисования MixArt Resin. 1,5 кг',
          orderId: '1583',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/neprozrachnye-matovye-krasiteli/krasitel-epoximaxx-colour-15-g-belyy/',
          id: '16058',
          measureName: 'шт',
          name: 'Краситель EpoximaxX Colour! 15 г белый',
          orderId: '1583',
          quantity: '1.0000',
        },
        {
          detailPageUrl: '/artbordy-i-planshety/5-artbordov-kruglye-30kh30-sm/',
          id: '16063',
          measureName: 'шт',
          name: '5 артбордов, круглые 30х30 см',
          orderId: '1583',
          quantity: '2.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T16:15:44+03:00',
      deducted: 'N',
      deliveryId: '42',
      deliveryName: 'СДЭК (Самовывоз)',
      id: '3169',
      orderId: '1584',
      statusId: 'DN',
      trackingNumber: 'CDEK 1217191250',
      items: [
        {
          detailPageUrl:
            '/epoksidnaya-smola/nabor-novichka-premium-s-epoxy-crystal-plus-115-g/',
          id: '16071',
          measureName: 'шт',
          name: 'Набор новичка PREMIUM с Epoxy Crystal PLUS, 115 г',
          orderId: '1584',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T16:22:30+03:00',
      deducted: 'N',
      deliveryId: '47',
      deliveryName: 'Самовывоз со склада-магазина',
      id: '3171',
      orderId: '1585',
      statusId: 'DN',
      trackingNumber: 'SAV 8121585',
      items: [
        {
          detailPageUrl:
            '/silikonovye-moldy/silikonovyy-mold-derzhatel-dlya-bokalov-3/',
          id: '16120',
          measureName: 'шт',
          name: 'Силиконовый молд Держатель для бокалов №3',
          orderId: '1585',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T16:35:58+03:00',
      deducted: 'N',
      deliveryId: '41',
      deliveryName: 'СДЭК (Доставка курьером)',
      id: '3175',
      orderId: '1587',
      statusId: 'DN',
      trackingNumber: 'CDEK 1217194370',
      items: [
        {
          detailPageUrl:
            '/epoksidnaya-smola/smola-dlya-khudozhestvennykh-rabot/smola-dlya-risovaniya/nabor-dlya-risovaniya-mixart-resin-box/',
          id: '16127',
          measureName: 'шт',
          name:
            'Premium набор для рисования MixArt Resin BOX. C прозрачной эпоксидной смолой.',
          orderId: '1587',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T19:09:55+03:00',
      deducted: 'N',
      deliveryId: '49',
      deliveryName: 'Главпункт (Пункты выдачи)',
      id: '3177',
      orderId: '1588',
      statusId: 'DN',
      trackingNumber: '',
      items: [
        {
          detailPageUrl:
            '/artbordy-i-planshety/artbord-pazl-iz-4-elementov-40kh40-sm/',
          id: '16176',
          measureName: 'шт',
          name: 'Артборд-пазл из 4 элементов, 40х40 см',
          orderId: '1588',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/artbordy-i-planshety/artbord-zheoda-imitatsiya-sreza-kamnya-60kh40-sm/',
          id: '16177',
          measureName: 'шт',
          name: 'Артборд. Жеода - имитация среза камня, 60х40 см',
          orderId: '1588',
          quantity: '1.0000',
        },
        {
          detailPageUrl: '/artbordy-i-planshety/5-artbordov-kruglye-10kh10-sm/',
          id: '16178',
          measureName: 'шт',
          name: '5 артбордов-подстаканников, круглые 10х10 см',
          orderId: '1588',
          quantity: '1.0000',
        },
        {
          detailPageUrl: '/artbordy-i-planshety/5-artbordov-kruglye-30kh30-sm/',
          id: '16179',
          measureName: 'шт',
          name: '5 артбордов, круглые 30х30 см',
          orderId: '1588',
          quantity: '1.0000',
        },
        {
          detailPageUrl: '/artbordy-i-planshety/artbord-monstera-45kh50-sm/',
          id: '16182',
          measureName: 'шт',
          name: 'Артборд Монстера, 45х50 см',
          orderId: '1588',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/artbordy-i-planshety/artbord-dlya-risovaniya-kvadratnyy-40kh40-sm/',
          id: '16189',
          measureName: 'шт',
          name: 'Артборд для рисования, квадратный 40х40 см',
          orderId: '1588',
          quantity: '1.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T19:05:18+03:00',
      deducted: 'N',
      deliveryId: '45',
      deliveryName: 'СДЭК (Самовывоз из ПВЗ (г.СПБ))',
      id: '3181',
      orderId: '1590',
      statusId: 'DN',
      trackingNumber: 'CDEK 1217210958',
      items: [
        {
          detailPageUrl:
            '/silikonovye-moldy/silikonovyy-mold-3d-yelka-so-zvezdoy-7-sm/',
          id: '16201',
          measureName: 'шт',
          name: 'Силиконовый молд 3D Ёлка со звездой 7 см',
          orderId: '1590',
          quantity: '2.0000',
        },
      ],
    },
    {
      allowDelivery: 'Y',
      dateAllowDelivery: '2020-12-06T22:27:51+03:00',
      deducted: 'N',
      deliveryId: '42',
      deliveryName: 'СДЭК (Самовывоз)',
      id: '3187',
      orderId: '1593',
      statusId: 'DN',
      trackingNumber: 'CDEK 1217225483',
      items: [
        {
          detailPageUrl: '/silikonovye-moldy/silikonovyy-mold-piramida-5-5sm/',
          id: '16233',
          measureName: 'шт',
          name: 'Силиконовый молд ПИРАМИДА 5*5см',
          orderId: '1593',
          quantity: '1.0000',
        },
        {
          detailPageUrl: '/silikonovye-moldy/silikonovyy-mold-kub-4-sm/',
          id: '16234',
          measureName: 'шт',
          name: 'Силиконовый молд "Куб" 4 см',
          orderId: '1593',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/instrument-i-sredstva-zashchity/silikonovyy-stakan-mernyy-100-ml/',
          id: '16235',
          measureName: 'шт',
          name: 'Силиконовый стакан мерный 100 мл',
          orderId: '1593',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/silikonovye-moldy/silikonovye-moldy-rascheski-2-sht/',
          id: '16236',
          measureName: 'шт',
          name: 'Силиконовые молды "Расчески" 2 шт',
          orderId: '1593',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/instrument-i-sredstva-zashchity/nabor-pintsetov-dlya-sozdaniya-ukrasheniy/',
          id: '16237',
          measureName: 'шт',
          name: 'Набор пинцетов для создания украшений',
          orderId: '1593',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/epoksidnaya-smola/uf-smola/uf-smola-uv-resin-hard-200-g/',
          id: '16238',
          measureName: 'шт',
          name: 'УФ смола UV Resin Hard 200 г',
          orderId: '1593',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/krasiteli/krasiteli-dlya-uf-smoly/perlamutrovye-krasiteli-kholodnogo-ottenka-dlya-uf-smoly-10-sht/',
          id: '16239',
          measureName: 'шт',
          name: 'Перламутровые красители холодного оттенка. 10 шт для УФ смолы',
          orderId: '1593',
          quantity: '1.0000',
        },
        {
          detailPageUrl:
            '/glittery/metallizirovannye-pigmenty/glitter-belyy-zhemchug-5-ml/',
          id: '16240',
          measureName: 'шт',
          name: 'Глиттер белый жемчуг, 5 мл',
          orderId: '1593',
          quantity: '1.0000',
        },
      ],
    },
  ],
  items: [
    {
      detailPageUrl:
        '/epoksidnaya-smola/smola-dlya-dekora-i-tvorchestva/yuvelirnaya-smola/yuvelirnaya-prozrachnaya-epoksidnaya-smola-epoximaxx-epoxy-crystal-plus-580-g-2-sht-/',
      id: '15181',
      measureName: 'шт',
      name:
        'Ювелирная прозрачная эпоксидная смола Epoximaxx Epoxy Crystal PLUS, 580 г, 2 шт.',
      orderId: '1511',
      quantity: '1.0000',
    },
    {
      detailPageUrl:
        '/krasiteli/prozrachnye-krasiteli/krasitel-epoximaxx-colour-15-g-chyernyy/',
      id: '15182',
      measureName: 'шт',
      name: 'Краситель EpoximaxX Colour! 15 г чёрный',
      orderId: '1511',
      quantity: '1.0000',
    },
    {
      detailPageUrl: '/silikonovye-moldy/mold-dlya-ukrasheniy-dva-bruska-/',
      id: '15184',
      measureName: 'шт',
      name: 'Молд для украшений "Два бруска"',
      orderId: '1511',
      quantity: '1.0000',
    },
    {
      detailPageUrl: '/silikonovye-moldy/mold-dlya-ukrasheniy-serdtse/',
      id: '15185',
      measureName: 'шт',
      name: 'Молд для украшений "Сердце"',
      orderId: '1511',
      quantity: '1.0000',
    },
    {
      detailPageUrl: '/silikonovye-moldy/mold-dlya-ukrasheniy-2-ovalnye-linzy/',
      id: '15186',
      measureName: 'шт',
      name: 'Молд для украшений "2 овальные линзы"',
      orderId: '1511',
      quantity: '1.0000',
    },
    {
      detailPageUrl: '/silikonovye-moldy/mold-dlya-ukrasheniy-tsilindr-/',
      id: '15187',
      measureName: 'шт',
      name: 'Молд для украшений "Цилиндр"',
      orderId: '1511',
      quantity: '1.0000',
    },
    {
      detailPageUrl:
        '/silikonovye-moldy/novogodnie/silikonovyy-mold-novogodnee-serdtse-12-sm/',
      id: '15238',
      measureName: 'шт',
      name: 'Силиконовый молд Новогоднее сердце 12 см',
      orderId: '1514',
      quantity: '1.0000',
    },
    {
      detailPageUrl:
        '/silikonovye-moldy/silikonovye-moldy-yelka-i-kolokolchiki-10-sm-3-sht/',
      id: '15239',
      measureName: 'шт',
      name: 'Силиконовые молды Ёлка и колокольчики 10 см 3 шт',
      orderId: '1514',
      quantity: '1.0000',
    },
    {
      detailPageUrl: '/silikonovye-moldy/mold-dlya-ukrasheniy-zvyezdy/',
      id: '15240',
      measureName: 'шт',
      name: 'Молд для украшений "Звёзды"',
      orderId: '1514',
      quantity: '1.0000',
    },
    {
      detailPageUrl: '/silikonovye-moldy/novogodnie/novogodnyaya-zvezda-24-sm/',
      id: '15241',
      measureName: 'шт',
      name: 'Силиконовый молд Новогодняя звезда 24 см',
      orderId: '1514',
      quantity: '1.0000',
    },
    {
      detailPageUrl:
        '/silikonovye-moldy/nabor-silikonovykh-moldov-zvezdy-serdtse-i-tsvetochek-4-sht/',
      id: '15242',
      measureName: 'шт',
      name: 'Набор силиконовых молдов "Звезды, сердце и цветочек" 4 шт',
      orderId: '1514',
      quantity: '1.0000',
    },
    {
      detailPageUrl:
        '/instrument-i-sredstva-zashchity/nabor-silikonovykh-mernykh-stakanov-po-100-ml-3-sht/',
      id: '15243',
      measureName: 'шт',
      name: 'Набор силиконовых мерных стаканов 100 мл. 3 шт',
      orderId: '1514',
      quantity: '1.0000',
    },
    {
      detailPageUrl:
        '/instrument-i-sredstva-zashchity/mikro-drel-s-naborom-5-svyerl/',
      id: '15244',
      measureName: 'шт',
      name: 'Микро дрель с набором 5 свёрл 1-3 мм',
      orderId: '1514',
      quantity: '1.0000',
    },
    {
      detailPageUrl:
        '/instrument-i-sredstva-zashchity/silikonovye-kovriki-dlya-raboty-s-epoksidnoy-smoloy-nabor-iz-3-sht/',
      id: '15245',
      measureName: 'шт',
      name: 'Силиконовые коврики для работы с эпоксидной смолой. Набор из 3 шт',
      orderId: '1514',
      quantity: '1.0000',
    },
    {
      detailPageUrl:
        '/epoksidnaya-smola/prozrachnaya-smola-epoximaxx-epoxy-crystal-plus-695-g-premium-nabor/',
      id: '15246',
      measureName: 'шт',
      name:
        'Прозрачная смола Epoximaxx Epoxy Crystal PLUS, 695 г (Premium набор)',
      orderId: '1514',
      quantity: '1.0000',
    },
    {
      detailPageUrl:
        '/epoksidnaya-smola/smola-dlya-zalivki/smola-dlya-stoleshnits/epoxymax-dekor-1-35kg04022388/',
      id: '15247',
      measureName: 'шт',
      name: 'Прозрачная эпоксидная смола EpoximaxX DECOR 1,35 кг',
      orderId: '1514',
      quantity: '1.0000',
    },
  ],
};
